import type { IconType } from "react-icons";
import {
  FaAmazon,
  FaApple,
  FaBandcamp,
  FaBehance,
  FaBook,
  FaCalendarAlt,
  FaCamera,
  FaDev,
  FaDiscord,
  FaDribbble,
  FaEnvelope,
  FaEtsy,
  FaFacebook,
  FaFigma,
  FaGamepad,
  FaGithub,
  FaGlobe,
  FaGooglePlay,
  FaHeadphones,
  FaHeart,
  FaInstagram,
  FaLink,
  FaLinkedin,
  FaMapMarkerAlt,
  FaMedium,
  FaMusic,
  FaNewspaper,
  FaPatreon,
  FaPaypal,
  FaPhone,
  FaPinterest,
  FaPodcast,
  FaRegUserCircle,
  FaReddit,
  FaRss,
  FaShoppingCart,
  FaSlack,
  FaSnapchat,
  FaSoundcloud,
  FaSpotify,
  FaStar,
  FaStore,
  FaTelegram,
  FaTelegramPlane,
  FaTiktok,
  FaTwitch,
  FaTwitter,
  FaVideo,
  FaWhatsapp,
  FaWordpress,
  FaYoutube,
} from "react-icons/fa";

// Bounded, statically-imported registry so the profile bundle stays under its JS
// budget (15-performance.md) — a namespace `import *` from react-icons/fa cannot
// be tree-shaken and would ship the entire icon set. Covers every ICON_OPTIONS
// social key plus the common link-prefix icons; unknown keys fall back to FaLink.
const FA_ICONS: Record<string, IconType> = {
  FaTwitter,
  FaSnapchat,
  FaRegUserCircle,
  FaDiscord,
  FaTiktok,
  FaInstagram,
  FaEnvelope,
  FaGithub,
  FaLinkedin,
  FaMedium,
  FaYoutube,
  FaFacebook,
  FaTelegramPlane,
  FaTelegram,
  FaTwitch,
  FaReddit,
  FaLink,
  FaGlobe,
  FaHeart,
  FaStar,
  FaMusic,
  FaSpotify,
  FaApple,
  FaAmazon,
  FaPodcast,
  FaPatreon,
  FaPaypal,
  FaBook,
  FaCalendarAlt,
  FaCamera,
  FaVideo,
  FaMapMarkerAlt,
  FaPhone,
  FaWhatsapp,
  FaPinterest,
  FaSoundcloud,
  FaBandcamp,
  FaGooglePlay,
  FaWordpress,
  FaEtsy,
  FaDev,
  FaBehance,
  FaDribbble,
  FaFigma,
  FaSlack,
  FaShoppingCart,
  FaStore,
  FaNewspaper,
  FaRss,
  FaGamepad,
  FaHeadphones,
};

export function getFaIcon(key: string | undefined): IconType {
  if (key && key in FA_ICONS) return FA_ICONS[key]!;
  return FaLink;
}
