export const BRAND_IMPERSONATION_KEYWORDS = [
  "bell",
  "rogers",
  "telus",
  "freedom mobile",
  "virgin mobile",
  "fido",
  "koodo",
  "verizon",
  "at&t",
  "att",
  "t-mobile",
  "tmobile",
  "vodafone",
  "orange",
  "spectrum",
  "xfinity",
  "comcast",
  "paypal",
  "chase",
  "wells fargo",
  "wellsfargo",
  "bank of america",
  "hsbc",
  "rbc",
  "royal bank",
  "td bank",
  "td canada trust",
  "scotiabank",
  "bmo",
  "citibank",
  "barclays",
  "revolut",
  "wise transfer",
  "fedex",
  "ups",
  "dhl",
  "usps",
  "canada post",
  "amazon",
  "coinbase",
  "binance",
  "kraken",
  "metamask",
  "trust wallet",
  "blockchain support",
  "customer support",
  "customer service",
  "account recovery",
  "account verification",
  "helpdesk",
  "verify your account",
] as const;

export const FREE_EMAIL_DOMAINS = new Set([
  "gmail.com",
  "yahoo.com",
  "outlook.com",
  "hotmail.com",
  "icloud.com",
  "protonmail.com",
  "proton.me",
  "aol.com",
  "mail.com",
  "gmx.com",
]);

export const SKETCHY_TLDS = new Set([
  "tk",
  "ml",
  "ga",
  "cf",
  "gq",
  "top",
  "xyz",
  "work",
  "click",
  "support",
  "link",
  "loan",
  "win",
  "review",
  "zip",
  "country",
]);

export const URL_SHORTENERS = new Set([
  "bit.ly",
  "tinyurl.com",
  "t.co",
  "is.gd",
  "cutt.ly",
  "rebrand.ly",
  "shorturl.at",
  "rb.gy",
  "buff.ly",
  "ow.ly",
  "s.id",
  "tiny.cc",
]);

export const URL_BLOCKLIST_PATTERNS = [
  "grabify.link",
  "iplogger.org",
  "iplogger.com",
  "2no.co",
  "blasze.com",
  "yip.su",
] as const;
